apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlation-processor
  labels:
    app: corrjoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corrjoin
  template:
    metadata:
      labels:
        app: corrjoin
    spec:
      nodeSelector:
        resultsVolumeMounted: "true"
      securityContext:
        fsGroup: 1001
      volumes:
         - name: results-store
           persistentVolumeClaim:
              claimName: receiver-results
      containers:
      - name: receiver
        image: localhost:5001/receiver:v0.1
        imagePullPolicy: Always
        command: ["/webroot/app"]
        args: ["-svdDimensions", "7", 
           "-windowSize", "100", "-stride", "50", 
           "-comparer", "inprocess", "-correlationThreshold", "99", "-justExplore" ]
        resources:
           limits:
              cpu: "1"
              memory: "4Gi"
           requests:
              cpu: "1"
              memory: "4Gi"
        ports:
        - containerPort: 9201
          name: api
        - containerPort: 9203
          name: metrics
        - containerPort: 9205
          name: explorer
        volumeMounts:
           - name: results-store
             mountPath: /tmp/corrjoinResults

