apiVersion: v1
kind: ConfigMap
metadata:
   labels:
      grafana_dashboard: "1"
   name: explore-metrics
data: 
  explore-metrics.json: |-
  {{- (.Files.Get "files/explore-metrics.json") | nindent 4 }}
