apiVersion: apps/v1
kind: Deployment
metadata:
  name: correlation-processor
  labels:
    app: corrjoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corrjoin
  template:
    metadata:
      labels:
        app: corrjoin
    spec:
      nodeSelector:
        resultsVolumeMounted: "true"
      securityContext:
        fsGroup: 1001
      volumes:
         - name: results-store
           persistentVolumeClaim:
              claimName: receiver-results
      containers:
      - name: receiver
        image: {{ .Values.image.repository }}/{{ .Values.image.image }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/webroot/app"]
        args: ["-svdDimensions", "5", 
           "-windowSize", "500", "-stride", "100", 
            #"-comparer", "inprocess", "-correlationThreshold", "99", "-justExplore", 
            "-comparer", "inprocess", "-correlationThreshold", "99", "-sampleInterval", "20",
           "-prometheusURL", {{ .Values.prometheusURL }},
           "-parquetMaxRowsPerRowGroup", "10000" ]
        resources:
           limits:
              cpu: "1"
              memory: "6Gi"
           requests:
              cpu: "1"
              memory: "4Gi"
        ports:
        - containerPort: 9201
          name: api
        - containerPort: 9203
          name: metrics
        - containerPort: 9205
          name: explorer
        volumeMounts:
           - name: results-store
             mountPath: /tmp/corrjoinResults

