{{- if not .Values.cni.useCeph -}}
apiVersion: v1
kind: PersistentVolume
metadata:
   name: receiver-results
spec:
   accessModes:
      - ReadWriteOnce
   storageClassName: local-storage
   capacity:
      storage: 1Gi
   volumeMode: Filesystem
   nodeAffinity:
     required:
       nodeSelectorTerms:
         - matchExpressions:
           - key: resultsVolumeMounted
             operator: Exists
   local:
      path: /tmp/corrjoinResults
   persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: receiver-results
   namespace: default
spec:
   volumeName: receiver-results
   storageClassName: local-storage
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: 1Gi
{{- end -}}
