{
 "title": "Postgres",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DB Active time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_active_time_seconds_total{datname=\"mattermost_main\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mattermost db tuple stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"mattermost_main\"}",
     "legendFormat": "tuples fetched"
    },
    {
     "expr": "pg_stat_database_tup_deleted{datname=\"mattermost_main\"}",
     "legendFormat": "tuples deleted"
    },
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"mattermost_main\"}",
     "legendFormat": "tuples inserted"
    },
    {
     "expr": "pg_stat_database_tup_returned{datname=\"mattermost_main\"}",
     "legendFormat": "tuples returned"
    },
    {
     "expr": "pg_stat_database_tup_updated{datname=\"mattermost_main\"}",
     "legendFormat": "tuples updated"
    }
   ]
  },
  {
   "title": "commits and rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "pg_stat_database_xact_rollback", "legendFormat": "rollbacks in {{datname}}" },
    { "expr": "pg_stat_database_xact_commit", "legendFormat": "commits in {{datname}}" }
   ]
  },
  {
   "title": "max tx duration on mattermost_main",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname=\"mattermost_main\", state!=\"idle\"}",
     "legendFormat": "max tx duration {{state}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "Activity count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"}",
     "legendFormat": "activity count db {{datname}} wait_event {{wait_event}}"
    }
   ]
  }
 ]
}