FROM golang:1.22 AS build

WORKDIR /src
COPY . .

RUN go mod download
RUN go vet -v ./...
RUN go test -v ./...

RUN CGO_ENABLED=0 go build -C frontend -o app

FROM gcr.io/distroless/static-debian12:nonroot

WORKDIR /webroot
COPY --from=build /src/frontend/app .
COPY --from=build /src/frontend/templates templates
USER 65532:65532
CMD ["/webroot/app"]

