# Override this on the commandline
password: editme

serviceAccount:
  name: postgres-sa

cni:
  useCeph: false
  createPv: true

mmdb:
  dbuser: ps_user
  name: mattermost_main

postgresNodeSelector:
   nodeSelector:
      postgresVolumeMounted: "true"

