# Registries defined within cri-o.
# crio_insecure_registries:
#   - 10.0.0.2:5000

# Auth config for the registries
# crio_registry_auth:
#   - registry: 10.0.0.2:5000
#     username: user
#     password: pass
---
crio_registries_mirrors:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: registry-1.docker.io
    mirrors:
      - location: mirror.gcr.io
        insecure: false

crio_pids_limit: 4096
