{
 "title": "loadtest performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Loadtest request times: 95th percentile",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(loadtest_http_request_time_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "loadtest request time buckets",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "loadtest_http_request_time_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "mattermost pod cpu load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"mattermost\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadtest requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "loadtest_http_requests_total",
     "legendFormat": "{{method}} on {{path}} returned {{status_code}}"
    }
   ]
  }
 ]
}