apiVersion: v1
kind: Secret
metadata:
  name: mattermost-postgres
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_CHECK_URL: postgres://{{ .Values.mmdb.dbuser }}:{{ .Values.password }}@postgres.postgres:5432/{{ .Values.mmdb.name }}?sslmode=disable
  DB_CONNECTION_STRING: postgres://{{ .Values.mmdb.dbuser }}:{{ .Values.password }}@postgres.postgres:5432/{{ .Values.mmdb.name }}?sslmode=disable
  MM_SQLSETTINGS_DATASOURCEREPLICAS: postgres://{{ .Values.mmdb.dbuser }}:{{ .Values.password }}@postgres.postgres:5432/{{ .Values.mmdb.name }}?sslmode=disable

