correlationServiceAddress: "http://correlation-service.default:9205"

image:
   repository: "ghcr.io/kpaschen"
   pullPolicy: "IfNotPresent"
   version: cluster-explorer
   image: corrjoin

serviceAccount:
   create: true
   name: "corrjoin-sa"

grafana:
   # You probably want to override this on the commandline.
   password: correlations!

# I don't currently have enough cpu in the cluster to run ceph.
cni:
  useCeph: false
  createPv: false  

prometheusURL: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"

