apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mm-corrjoin
  namespace: mattermost
spec:
  replicas: 1
  size: 100users
  ingress:
    enabled: false
    host: corrjoin.nephometrics.com
  version: 9.3.0
  database:
    external:
       secret: mattermost-postgres 
  fileStore:
     local:
        enabled: true
        storageSize: 10Gi
