apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
   name: receiver-monitor
   labels:
      app.kubernetes.io/instance: prometheus
spec:
   selector:
      matchLabels:
         app: corrjoin
   endpoints:
   - port: metrics

