{
 "title": "Apache HTTP server",
 "tags": [ "apache-http-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(apache_up, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(apache_up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_info{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "apache info"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "apache_up{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Apache up"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Calls"
    },
    {
     "expr": "rate(apache_sent_kilobytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 1000",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(apache_duration_ms_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])/increase(apache_accesses_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Average response time"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_scoreboard{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "apache scoreboard"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{job=~\"$job\", instance=~\"$instance\"}\n",
     "legendFormat": "apache workers"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_cpuload{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Load"
    }
   ]
  }
 ]
}