apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: apache
          securityContext:
            allowPrivilegeEscalation: false
          image: 'docker.io/library/httpd:2.4.63'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
          - name: apache-config
            #mountPath: /usr/local/apache2/conf/httpd.conf
            mountPath: /configs
      volumes:
        - name: apache-config
          configMap:
             name: apache-config
 
