apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apache-monitor
  namespace: apache
  labels:
     app.kubernetes.io/instance: prometheus
spec:
  selector:
    matchLabels:
      app: apache-exporter
  podMetricsEndpoints:
  - port: metrics
