apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: apache
  labels:
    app: apache
spec:
  ports:
    - port: {{ .Values.port }}
      name: mattermost
    - port: {{ .Values.metricsPort }}
      name: metrics
  selector:
    app: apache
