name: Run tests
run-name: Test ${{ inputs.tag }}
on:
   workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazel-contrib/setup-bazel@0.8.1
      - name: blaze test
        run: blaze test //...
          
